name: Monitor Famous GitHub Actions

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    env:
      # These should be set in your repository secrets or .env file
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3 on 2025-06-26, TODO: consider using a release

      - name: Set up Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4 on 2025-06-26, TODO: consider using a release
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv

      - name: Create .env file from secrets (if needed)
        run: |
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" > .env
          echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}" >> .env
        shell: bash

      - name: Run monitor for famous actions
        run: |
          python monitor_action.py \
            tj-actions/changed-files,reviewdog/action-super-linter,actions/checkout,actions/setup-python,actions/cache,github/codeql-action,actions/upload-artifact,actions/download-artifact,actions/setup-node,actions/setup-java,actions/setup-go \
            --baseline-dir baselines

      - name: Commit and push updated baselines
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add baselines/
          git commit -m "chore: update baselines [auto]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 